<?php

namespace Ekyna\Component\Commerce\Product\EventListener\Handler;

use Ekyna\Component\Commerce\Product\Model\ProductInterface;
use Ekyna\Component\Commerce\Product\Model\ProductTypes;
use Ekyna\Component\Resource\Event\ResourceEventInterface;

/**
 * Class ConfigurableHandler
 * @package Ekyna\Component\Commerce\Product\EventListener\Handler
 * @author  Etienne Dauvergne <contact@ekyna.com>
 */
class ConfigurableHandler extends AbstractHandler
{
    /**
     * @inheritDoc
     */
    public function handleInsert(ResourceEventInterface $event)
    {
        // TODO: Implement handleInsert() method.
    }

    /**
     * @inheritDoc
     */
    public function handleUpdate(ResourceEventInterface $event)
    {
        // TODO: Implement handleUpdate() method.
    }

    /**
     * @inheritDoc
     */
    public function handleDelete(ResourceEventInterface $event)
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function handleStockUnitChange(ResourceEventInterface $event)
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function handleChildStockChange(ResourceEventInterface $event)
    {
        // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function supports(ProductInterface $product)
    {
        return $product->getType() === ProductTypes::TYPE_CONFIGURABLE;
    }
}
